#+TITLE: EDUCTN 750/1 Notes
#+AUTHOR: Curtis D'Alves

* Expectations for Co-Facilitating Class Discussion
 - Sign-up sheet https://docs.google.com/spreadsheets/d/1u74JQ-X58bcsbA_pnwgQL9QaJr5sv9nc_qOjFoKza-E/edit?usp=sharing
 - You will facilitate a 20-minute discussion on the required readings/viewings
   for the week you've selected - budget your time!
   - Facilitate a class discussion - not other learning strategies
   - Provide a brief summary (5 min no more, in addition to 20 min of
     discussion)
 - *Collaborate* with other facilitators signed up for that week to develop a
   set of discussion questions focused on key takeaways
 - Ensure all learners are given an opportunity to participate
 - After the discussion, you will receive peer feedback on both your questions
   and your facilitation
   
* Week01
** Andrews' (1980) Four Categories for Classifying Questions
*** Question Level
  Cognitive skills required to answer the question 
   | *Low Level*                                | *High Level*                                             |
   +--------------------------------------------+----------------------------------------------------------+
   | Rote memory of simply rephrasing materials | Requires operations of analysis,synthesis and evaluation |
   | e.g. who are the main characters in hamlet | e.g. what about Laerte's role... could he be left out of |
   |                                            | the book and it would still be Hamlet?                   |

*** Convergence/Divergence
   Number of acceptable answers that are implied in the question
   | *Convergence*                               | *Divergence*                          |
   +---------------------------------------------+---------------------------------------+
   | - Implies there is a single answer          | - A number of plausible answers       |
   | - Increases risk, and requires more time to | - Safer to venture a viewpoint, and   |
   | think through a response                    | more spontaneity in responses         |
   | e.g What is the boiling point of water      | e.g. What happens when you boil water |

*** Structure
    Whether it provides contexts/guidelines through which the learner can
    prepare an answer
    | *Unstructured*                               | *Structured*                                |
    +----------------------------------------------+---------------------------------------------+
    | - Wide open                                  | - Directs the learner to specific           |
    |                                              | approaches/subject areas                    |
    | - Requires more time to organize response    | - Arrive at response more quickly           |
    | e.g. What did you think of the bridge design | e.g. What are some factors that contributed |
    |                                              | to the failing of the bridge?               |

*** Straightforwardness
    Amount of related information interspersed with the question
    | *Multiple*                               | *Straightforward*                                |
    +------------------------------------------+--------------------------------------------------+
    | - Contains several questions or is       | - Singular in nature, allowing learners to focus |
    | interspersed with background information | on one issue at a time                           |
    | - Unlikely learners wjill know what is   | - Increases likelihood learners have heard the   |
    | being asked of them or hear the          | question as stated                               |
    | questions as stated                      |                                                  |

* Week02

** Understanding by Design
   - Lessons, units and courses should be logically inferred from the results
     sought, not derived from the methods, books ,and activities with which we
     are most comfortable
   - the best designs derive backward from the learnings sought
   - Many teachers remain focused on the inputs (textbooks, favored lessons,etc)
     rather than the output (desired results)
   - Another name for this is /content/-focused vs /results/-focused
   - *twin-sins of traditional design*:
     - *activity oriented design* leads to "hands-on without being minds-on"
       engaging experiences that lead only accidentally (if at all) to insight
     - *coverage approach* has students march through a textbook in an attempt to
       traverse through all factual material within a prescribed time
   - In neither the above cases can students see: What's the point? What does
     this help us understand or be able to do? To what does this relate? What's
     the big idea here? Why should we learn this?
*** Three Stages of Backward Design
**** Stage 1: Identify desired results
     - What should students know, understand, be able to do?
     - Consider our goals, examine established content standards
       (national,state,district), and review curriculum expectations
**** Stage 2: Determine acceptable evidence
     - How will we know if students have achieved the desired results?
     - What will we accept as evidence of student understanding and proficiency?
**** Stage 3: Plan learning experiences and instruction
     - think through the most appropriate instruction activities while thinking
       about:
       - What enabling knowledge (facts,concepts, principles) and skills
         (processes,procedures,strategies) will students need?
       - What activities will equip students with the needed knowledge and skills?
       - What will need to be taught and coached?
       - What materials and resources are best suited to accomplish these goals?

** Intended Learning Outcomes (ILOs)
   Statements that specify what the learner will know and be able to do by the
   end of the learning experience, can be divided into 3 components:
   - *Action Verb*: identifies the depth of learning expected and beings to
     inform learners about how they will apply the knowledge/skill they have gained
   - *Statement specifying the learning to be demonstrated*: should be a skill
     or particular knowledge on a topic
   - *Statement giving context/linking to activities and/or assessments*:
     (optional)
*** Example:
    - Analyze
    - the research design of a peer-reviewed journal article
    - by completing the article Evaluation worksheet

*** Smart ILOs
    Every ILO should be Smart:
    - Specific
    - Measurable
    - Action Oriented
    - Results-Oriented
    - Timely and Tangible

* Week 03
  See [[file:./assessemnts/week03/]], worksheet all about difference online
  resources like avenue, teams, webex, zoom, etc
  
* Week 04

** Active Learning
   Doing + Reflection
    - "involving students in doing things and thinking about what they're doing"
      Bonwell & Einson

*** 4 Key Elements
    1) Critical thinking
    2) Individual responsibility for learning
    3) Involvement in open-ended flexible activities
    4) Organization and facilitation of leaning activities by the instructor

*** Why use active learning?
    Active learning can:
    - provide more frequent and immediate feedback for students
    - Provide opportunies for students to discuss content and learn from one
      another
    - Facilitate students' skill development
    - Encourage students to consider how content applies to real word
      situations
    - Create a sense of community

*** The Segmented Lecture
    
    |-------------------+-----------------+-------------------+-----------------+-------------------|
    | Lecture (<15 min) | Active Learning | Lecture (<15 min) | Active Learning | Lecture (<15 min) |
    |-------------------+-----------------+-------------------+-----------------+-------------------|
  
*** Considerations when Introducing Active Learning
   Ensure the active learning activity is:
   - Normalized at an early point in the course
   - Authentically connected to course content and skill development, with clear
     value to students
   - Focused on a few key ideas
   - Supportive of all students (make sure the classroom is a welcoming
     non-discrimitory space)

** Measuring actual learning versus feeling learning
   - Despite scoring hiring on test scores with active learning, students resist
     active learning expressing preference for passive instruction
   - Students in active classes perceived that they learned less, when in
     reality they learned more

* Week 05
  
** Universal Design for Learning in Postsecondary Education
  - *Universal design* involves designing products, buildings, or environments so
    they can be used readily by the widest range of users.
  - Universal design has been well established in architecture and other domains
    (i.e. *built environments*) but lags behind in the *learning environment*.
  - This lag may reflect the reality that the *idea* of universal design transfers
    readily from the built environment to the learning environment but it's
    *principles* and *techniques* do not


*** Assistive technologies
    specifically designed to assist individuals with disabilities in overcoming
    barriers in their environment
    
    - Universal design focuses on eliminating barriers through initial designs
      that consider the needs of diverse people, rather than overcoming barriers
      later through individual adaptation (i.e. avoids Assistive technologies
      that are put there to overcome an unnecessary barrier)

*** Accessible pedagogy as three specific and central considerations
    - the means of representing information
    - the means for students' expression of knowledge
    - the means of engagement in learning 

*** Universal Design for Learning vs Universal Design in other domains
    The principles central to UDL focus on learning, and thus are different from
    the well-known principles for making the physical environment universally designed

*** Three Principles for UDL
**** Principle One: Multiple Means of Representation
     Students differ in the way they perceive and comprehend information, and
     there is no common optimal means of representing information to address
     diverse learners' need. Hence multiple means of representation of
     information that cover as many modes of accessibility as possible is key
     
**** Principle Two: Multiple Means of Expression
     Students differ in the ways they can navigate a learning environment and
     express what they know, many students are able to express themselves much
     more capably in one medium than another (i.e. audio or video editing rather
     than writing). This is just one aspect of expression in UDL however, it
     must also deal with accessible alternatives to the various scaffolds and
     supports provided for student learning (i.e. providing alternatives in
     mentoring, modeling various scaffolding that can gradually be release as
     students gain competency, and feedback)

     - TL;DR: reflects the fact there is no one means of expression that will be
       optimal for all students, nor one kind of scaffolding or support that
       will help them as they learn to express themselves
       
**** Principle Three: Multiple Means of Engagement
    Students differ in the ways in which they are engaged or motivated to learn.
    This is both extrinsic (adding motivating elements to the learning
    environment) and intrinsic (students must also develop internal standards
    and motivation, which requires more subtle rewards of accomplishment and
    choice)
     
*** Basis for UDL and it's Principles
    - The framework for UDL is based in findings from cognitive neuroscience that
      tell us about the needs of individual learners.
    - The three principles reflect the basic neurology of the learning brain,
      broadly speaking, they reflect three general components:
      + one that learns to recognize objects or patterns in the external
        environment (*Recognition Networks*)
      + one that learns to generate effective patterns of action or response
        (*Strategic Networks*)
      + one that learns to evaluate the significance or importance of possible
        patterns we encounter or generate (*Affective Networks*)

*** Applications of UDL in a University Course
    The paper details a case study of a semester long course:
    - *T-560: Meeting the Challenge of Individual Differences*
    - Offered at Harvard Graduate School of education, 2004-2005
    - 93 graduate students registered, with diverse background and interests
    - Majority of students came three ares:
      + human development (especially mind, brain and education)
      + technology in education
      + teaching and curriculum development
**** Applying UDL Principles to Course Lectures
***** Lectures
     - Lecture's play an important role, good lectures use not just speech but facial expression,
       gesture and body motion to further convey meaning and affect, as well as
       additional media such as Power-Point
     - Alternative representations of lectures are provided, differing in the
       kinds of problems they seek to address, the ease of implementation, and
       the kinds of technologies they require
       + lecturers are assisted by sign language interpreters
       + lecturer attempts to also orally describe visuals
       + each lecture is videotaped and distributed via the course web site
       + student notes are collected and displayed for everyone
     - Good lecturers use a variety of techniques to make their structure more
       explicit and memorable, and to reduce the cognitive load required, i.e.
       + using more repetition than in written text
       + explicitly stating structure
       + explicitly summarizing where the argument has come so far
***** Power Point
     - Power-Point slides are a nearly constant accompaniment and used in two
       primary ways:
       + to clarify and make explicit the structure of the talk (don't overuse
         the slides in "bullet-point" where speaker simply reads slides to
         audience). Text should mainly be used to introduce a new topic or
         summarize a previous section, i.e. they provide structure not substance
       + During the main part of lectures, slides are primarily graphic or
         visuals
***** Discussion Groups
     - Discussion Groups are applied with UDL principles in mind by:
       + having students choose among different discussion groups (also all are optional)
       + having "review" sessions where no new info is presented but students
         ask questions and participate in guided review discussions, express
         concerns, etc
       + having "advanced" sessions that discuss something that extends or
         challenges material (assuming students already know it)
       + students have choice of medium, face-to-face or online
***** Textbooks
     - Textbooks are not promising foundation for UDL because inherently
       inflexible, but are still used for their virtues, also
       + two textbooks are chosen that cover the same topics, syllabus
         recommends student purchase and read only one of them
       + one book is available online
***** Multimedia (the course Website)
     - A course website is used as a frame that holds the syllabus, the
       assignments, the discussion groups, the projects, the class notes, the
       class videos, the PowerPoint slides and much more
     - An advantage of websites is the rich set of media of which they are
       constructed, the course website contained not only links to readings but
       other high quality websites that can be highly engaging
***** Assessment Methods
     - Considering assessment in UDL focuses on the second principle: providing
       multiple means of action and expression
     - Students complete two projects which they are graded on:
       + midterm project that requires them to review the research literature on
         one type of learner and to create a website. 
       + final project to design a lesson or curriculum that considers the
         profile of the learner in their first projects
     - The projects can be not only text, but also images, sound, video, the web
       and so forth. The word count is limited to 1500. When finished must
       submit in form of website

** The Myth of Learning Styles

   - There is no credible evidence that learning styles exist
   - The claim at the center of *learning-styles theory* is this: Different
     students have different modes of learning, and their learning could be
     improved by matching one's teaching with that preferred learning mode
   - Although the definition of "modes of learning" has changed over it's 50
     years of use, the most popular current conception equates style with the
     preferred bodily sense through which one receives information (be it
     visual, auditory, or kineshetic)
   - The article acknowledges three true claims from learning theorists:
     + learners are different from each other, these differences affect their
       performances and teachers should take these differences into account
     + students differ in their interests
     + students differ in their background knowledge 
   - So claiming learning styles do not exist is not saying that all learners
     are the same, but the emphasis on learning styles comes at the cost of
     attention to other important dimensions
   - The article asserts the following claims in learning style theory are wrong
     + learners have preferences about how to learn that are independent of both
       ability and content and have meaningful implications for their learning
     + learning could be improved by matching the mode of instruction to the
       preferred learning style of the student
   - The article asserts the burden of proof is on the learning styles theorists
     and is unfulfilled, and we should only bring ideas from laboratory into
     teaching if:
     + we are sure that the laboratory phenomena exist under at least some
       conditions
     + we understand how to usefully apply these laboratory phenomena to
       instruction
   - The article asserts the belief in learning styles persists because of two
     positive consequences stemming from the true claims of learning theorists:
     + teachers should take into account the differences in learners' ability
     + learning styles fits into an egalitarian view of education: everyone has
       value and strengths
   - Learning styles theory also persists because it has succeeded in becoming
     "common knowledge"
   - The article asserts there are opportunity costs to embracing learning
     styles theory, in summary we present information in the most appropriate
     manner for our content and for the level of prior knowledge, ability and
     interests of the particular set of students

   
#  LocalWords: UDL WebSite Website PowerPoint website websites kineshetic

* Week 06
** Teaching Philosophy Statements
  Teaching Philosophy statements clearly communicate our beliefs about teaching
  and learning, why we hold these beliefs, and how we translate them into practice 
  
*** What Does a Teaching Philosophy Statement Look Like?
    Teaching philosophies are typically one to two-page reflective documents
    written as first-person narratives. They can be broken down into an
    introductory section that summarizes core beliefs and why you hold them, a
    section providing an overview of specific strategies you use to align with
    these beliefs, and final sections highlighting the impact that your teaching
    and learning approaches have had on yourself and others (this section may
    also highlight methods you use to assess your teaching)

    Use the following guiding questions to construct a Teaching Philosophy Statement
**** Beliefs (What do you think?)
     What are my beliefs about teaching and learning in post-secondary education?
     Why do I hold these beliefs? Who or what has most informed my teaching
     approaches? What are the best learning experiences I had as a student?
     How have my beliefs been influenced by my teaching experiences and/or
     scholarly literature related to teaching and learning? What difference
     do I hope to make as a teacher? What does it mean to be a good teacher
     in a post-secondary context? What does good teaching look like in my
     discipline? What does it mean to be a good learner in a post-secondary
     context?
**** Strategies (What do you do?)
     What teaching and learning strategies do I use? How do these strategies align with
     my beliefs? What are the best teaching experiences I had as an instructor? When
     have I felt most engaged and affirmed as an instructor? What are my key strengths
     and skills as an instructor? Why do I use particular teaching strategies as opposed
     to others? What am I proudest of? What sets me apart? What are some of my
     accomplishments as a post-secondary educator?
**** Impact (What is the effect on learners, self, colleagues?)
     What difference have I made, and how do I know? What am I trying to achieve in
     my students with my teaching? What has been the impact of my approaches to
     teaching and learning (on me, on students, on colleagues)? What have others
     learned from my teaching and learning approaches? What methods do I use to
     evaluate my impact?
**** Future Goals (How will you improve?)
     How will I continue developing, growing and improving as an educator? What
     interests me most about teaching in post-secondary education? What are my
     future goals and aspirations as an instructor in post-secondary education?
     
*** Processes for Developing A Statement As Outlined in Literature
   The following principles have been adapted by Kenny (2014) from
   Chickering and Gamson’s (1987) seven principles for good practice in undergraduate education,
   Ramsden’s (2003) thirteen principles for effective university teaching; Weimer’s (2013) five key
   changes to practice for learner-centred teaching, and Lizzio et al.’s (2002) conceptual model for
   an effective academic environment.

**** Actively Engage Learners
     ensure learning material is stimulating, relevant and interesting; explain
     material clearly; use a variety of methods that encourage active and deep
     approaches to learning, as well as adapt to evolving classroom contexts.

**** Demonstrate Passion, Empathy and Respect
     show interest in students’ opinions and concerns; seek to understand their
     diverse talents, needs, prior knowledge and approaches to learning;
     encourage interaction between instructor and students; share your love of
     the discipline.

**** Communicate Clear Expectations
     make clear the intended learning outcomes and standards for performance;
     provide organization, structure and direction for where the course is
     going.

**** Encourage Student Independence
     provide opportunities to develop and draw upon personal interests; offer
     choice in learning processes and modes of assessment; provide timely and
     developmental feedback on learning; encourage metacognition to promote
     self-assessment of learning.

**** Create a Teaching and Learning Community
     use teaching methods and learning strategies that encourage mutual
     learning, as well as thoughtful, respectful and collaborative engagement
     and dialogue between all members of the classroom community.

**** Use Appropriate Assessment Methods
     clearly align assessment methods with intended course outcomes; provide
     clear criteria for evaluation; emphasize deep learning; scaffold
     assessments to ensure progressive learning.

**** Commit to Continuous Improvement
     gather formative and summative feedback on your teaching; practice critical
     self-reflection; consult scholarly literature on teaching & learning;
     engage in meaningful conversations with colleagues; identify clear goals
     for strengthening your teaching practice.
       
*** Lecture: Guiding Questions
**** 1. Defining Teaching and Learning
     - What are my beliefs about teaching?
       + Broadly speaking teaching is a form of assisted learning when one
         person assumes the role of teacher. When a person assumes the role of
         teacher, they take on the responsibility of guiding a learners
         experience. Conversely the learner must engage in a certain degree of
         trust with the teacher.
         
     - What is good teaching?
       + Good teaching is effective teaching, i.e. teaching that effectively
         results in the learner gaining the knowledge / understanding of
         concepts being taught. 
         
     - What is my role as teacher?
       + A teacher broadly fulfills two roles; an instructional role that
         directs/guides students through learning material, and a reinforcement
         role that challenges and assesses students progress, supporting them
         when they fail.

     - Why do I hold these beliefs?
       + My beliefs about teaching are formulated from personal experience as
         both student and teacher.

     - What experiences have influenced my teaching and/or my beliefs?
       + Both of my parents were high school teachers. As a child I often heard
         my parents discuss concerns for different troubled students over the
         dinner table. I was always aware of the responsibility they felt to
         their students and as I grew older I came to recognize this quality in
         other teachers that stuck out in my mind as "good" teachers. 
         
**** 2. The Learner & The Student-Teacher Relationship
     - How do students learn? How do I help them learn?
       + Students learn through applying concepts (i.e. in exercises or through
         performance) that have been presented to them (i.e. through lectures,
         textbooks, etc). A teacher helps students learn by providing them with
         this material (both the presentation of concepts and how to apply them)
         in a guided framework
     - What's the student's role in the classroom/learning environment?
       + The students role is to engage with the material presented to them in a
         timely fashion and seek help when needed
     - What is my relationship with my students? How do I foster this relationship?
       + My relationship with my students is as a mentor that can provide them
         with the guidance needed to learn what concepts in what order and from
         where 
     - What is important in student-teacher interaction?
       + An optimal student-teacher interaction provides the student with the
         confidence and direction needed to attempt to tackle the problem at
         hand, while feeling comfortable enough to re-approach the teacher
         whenever a road-block is next encountered 

**** 3. Your Approach to Teaching & Evaluation
     - What methods do I use to teach? To assess?
       + I teach through example, identifying an interesting problem to solve
         and illustrating how I approach and solve said problem while
         highlighting important concepts I use along the way. I assess by
         observing students ability to do the same, i.e. not just solving a
         problem but how they arrive at the solution and their ability to
         understand underlying concepts used to do so
     - What are my strengths in teaching? In assessment?
       + My strengths in teaching are my ability to work through a problem in
         real time, not perfectly but with mis-steps that I can correct and turn
         into a learning experience. My strengths in assessment is my ability to
         see where students are failing/misunderstanding, even if they are able
         to arrive at a correct solution
     - How do I know if students are learning? How do they know?
       + On-going assessment and feedback let's me and my students know if they
         are learning. It's important to intersperse assessment activities with
         learning in such a way that the student feels they are continuously
         receiving feedback on their learning progress.
     - How does my discipline influence my teaching? My assessments?
       + Fortunately computer science is a prime field to implement a learning
         environment with frequent, on-going assessment during the learning
         experience. Learning environments for computer science should always
         focus around interfacing with a computer, which is capable of
         automating a great deal of feedback. 
     - How do my teaching methods complement my teaching context
       (institutional,departmental,disciplinary?) My assessments?
       + 

* Week 07
** Constructing a Learner-Centered Syllabus
   The first day of class is usually an overview of the course syllabus, after
   which you might ask yourself "What is the purpose of my syllabus? My Students
   seemed very disengaged today. Why? Now that I think of it, the syllabus
   doesn't match who I am as a teacher. Why not?"

   There is an increasing amount of available research on best practices in
   syllabi construction. A growing body of research practice suggests that
   learner-centered syllabi can have several positive impacts.

*** Purpose of a Syllabus: Historical Review
    - syllabus is views as a contract, i.e. defines and establishes the
      respective duties, roles and responsibilities of the students and teacher
    - syllabus is considered a permanent record that contains all the details
      and accurate information about the course requriments and content
    - syllabus can serve as a cognitive map and learning tool for students
*** How to Construct a Learner-Centered Syllabus
    - Begin with a teacher centered syllabus and convert to a learner-centered one
    - Cullen and Harris (2009) describe several key qualities of a
      learner-centered syllabus, including:
      + the major factors that establish community (e.g. accessibility of the
        teacher, the role of collaboration and a learning rationale)
      + those that define the balance of power and control between student and
        teacher (e.g., the teacher’s role, the student’s role, outside
        resources, and syllabus focus)
      + those of evaluation and assessment nt (e.g., grades, feedback
        mechanisms, evaluation, desired learning outcomes, and revision/redoing)

        
* Week 09
  
** Conditions Under Which Assessment Supports Students' Learning
*** The dominant influence of assessment
    They are strategic in their use of time and ‘selectively negligent’ in avoiding
    content that they believe is not likely to be assessed. It has been claimed
    that students have become more strategic with their use of time and energies
    since the 1970s and more, rather than less, influenced by the perceived
    demands of the assessment system in the way they negotiate their way through
    their studies (MacFarlane, 1992).
*** The role of Coursework Assignments
    - Students tend to gain higher marks from coursework assignments than they do
      from examinations
    - Students also prefer coursework. Starr (1970) reported that 90% of students
      from four departments preferred half or more of their marks to come from
      Coursework and 56% preferred all their marks to come from Coursework
    - Coursework marks are a better predictor of long term learning of
      course content than are exams
    - in experimental studies in which students have either studied exam-based
      or assignment-based courses, the quality of their learning has been shown
      to be higher in the assignment-based courses.
*** The decline of formative assessment
    Resource constraints in conventional universities have led to a reduction in the
    frequency of assignments, in the quantity and quality of feedback and in the
    timeliness of this feedback. 
*** The effectiveness of feedback
    In a comprehensive review of 87 meta-analyses of studies of what makes a
    difference to student achievement, Hattie (1987) reports that the most
    powerful single influence is feedback.

    School-based research has identified lists of effects of formative assessment
    such as the one below, based on Gagne (1977):
      1.Reactivating or consolidating prerequisite skills or knowledge prior to introducing the new
        material
      2.Focusing attention on important aspects of the subject
      3.Encouraging active learning strategies
      4.Giving students opportunities to practise skills and consolidate learning
      5.Providing knowledge of results and corrective feedback
      6.Helping students to monitor their own progress and develop skills of
        self-evaluation
      7.Guiding the choice of further instructional or learning activities to
        increase mastery
      8.Helping students to feel a sense of accomplishment
      
      The conditions outlined here refer to two relatively distinct categories of
      influence:
        • the influence of the design of assessment systems and assignments on
          how much students study, what they study and on the quality of their
          engagement
        • the influence of feedback on learning.

*** Influences of assessment on the volume, focus and quality of studying
    - *Condition 1* Sufficient assessed tasks are provided for students to
      capture sufficient study time
    - *Condition 2* These tasks are engaged with by students, orienting them to
      allocate appropriate amounts of time and effort to the most important
      aspects of the course
    - *Condition 3* kling the assessed task engages students in productive
      learning activity of an appropriate kind
*** Influence of feedback on learning
    - *Condition 4* Sufficient feedback is provided, both often enough and in enough detail
    - *Condition 5* feedback focuses on students’ performance, on their learning
      and on actions under the students’ control, rather than on the students
      themselves and on their characteristics
    - *Condition 6* feedback is timely in that it is received by students while
      it still matters to them and in time for them to pay attention to further
      learning or receive further assistance
    - *Condition 7* feedback is appropriate to the purpose of the assignment and
      to its criteria for success
    - *Condition 8* feedback is appropriate, in relation to students’ understanding
      of what they are supposed to be doing
    - *Condition 9* feedback is received and attended to
    - *Condition 10* feedback is acted upon by the student
    
#  LocalWords:  Coursework
