#+TITLE: Teaching Philosophy Statement
#+AUTHOR: Curtis D'Alves
#+DATE: March 11, 2021

#+OPTIONS: toc:nil
#+LaTeX_CLASS: customarticle


* My core personal beliefs on teaching

  *Teaching is a responsibility*. When a person assumes the role of teacher,
  they take on the responsibility of guiding a learners experience. On the other
  hand, the learner must yield a certain degree of trust with the teacher. This
  is not to say a students learning experience solely relies on a teacher, but
  it is necessary to recognize this dynamic to effectively understand the role.
  It is a teachers responsibility to never betray the trust of a student, this
  responsibility is multi-faceted and vast but put broadly the teacher must
  always put the students well being first and foremost. This means results
  achieved by conventional means of assessment cannot be the teachers only
  priority.

  #+LATEX: \noindent
  *Good teaching challenges and inspires students*. A teacher should offer the
  students more than what can be offered through a textbook or pre-recorded
  lectures. A teacher should present students with challenges to overcome, and
  inspire them to want to do so of their own volition. I entered university with
  a singular goal, acquire a degree. However during my first year of university,
  I met a professor that I'd come to do a student research project with during
  the summer that would change my outlook on education. He presented me with an
  opportunity to do real research, and although I was highly under-qualified at
  the time he set up series of challenges/stepping stones that allowed me to
  work up to the level of competence necessary to be useful. I wish to inspire
  other students the way he inspired me.

  #+LATEX: \noindent
  *Teaching should be accessible*. Everyone should have access to education, and
  teachers should be aware and accommodating of different accessibility issues
  that their students may face. Teachers are often to quick to assume their
  methods of assessment or presentation are the only reasonably effective way to
  teach, and that it is the responsibility of the student to adapt to them no matter
  their circumstances. This loses sight of the true goals of teaching, to give
  students the skills and knowledge they need to succeed.
  
* My teaching strategies

  *I employ Active Learning methods in my lectures and teaching material*.
  Active learning makes use of various activities to break up the otherwise
  passive experience of learning in traditional lectures. It puts a higher
  degree of responsibility on the student, challenging them during the learning
  process. And there is possibly no more appropriate field to employ active
  learning then computing and software. Interfacing with a computer allows a
  level of live assessment not achievable otherwise. By interspersing lecture
  content with live coding activities and discussion sessions students have a
  much deeper level of engagement with the material, and receive a much more
  adequate level of feedback than conventional assessment methods. Regular
  lecture sessions cease to be a passive experience where students show up
  simply to listen to a professor present a topic and become a challenge for
  learners to overcome.

  #+LATEX: \noindent
  *I provide real world applications of concepts being taught wherever
  possible*. Most students in STEM come to university with the dream of one day
  acquiring the skills to build something truly useful. For these students, the
  traditional university experience can be extremely disheartening. Whole
  subjects (calculus for example) can seem like nothing more than a form of
  academic hazing, meant to give students a hard time rather than provide them
  with useful skills. When I taught my first sessional position, an experiential
  learning based course in the second semester of the first year in a CS
  program, I laid out a clear road map with an end goal of developing a Django
  stack (Javascript - Python - Django - MySQL) web app managed under a GitHub
  repository that they could showcase as part of their personal portfolio. I
  found that as long as I could relate the concepts I was teaching as part of
  this end goal students were far more inspired to engage with the content.

  #+LATEX: \noindent
  *I design my course content following Universal Design for Learning
  principles*. When appropriate, I provide course content in as many different
  means of representation as reasonable. This means implementing redundancies
  for visual and audio representation in lectures and video presentations, which
  can be as simple as making sure to fully explain slide content verbally and
  providing all verbally explained content in slides and text documents. I also
  encourage note sharing (either for bonus marks or a means of assessment with
  exemptions) to help students who have difficulty taking notes. Another
  principle of Universal Design for Learning I follow is providing students with
  multiple means of engaging with me. Although I encourage students to engage
  with me directly in class or during office hours, I understand in person
  experience can be anxiety inducing. I find online interfaces (like forums and
  instant messaging / video conferencing) can be very effective alternatives for
  these students.
  
* My goals as a teacher

  Although my teaching experience is limited, I already greatly value the
  positive impacts I've had on my students. Of all the feedback I've received,
  the most dear to me are from students from a different program who have stated
  they were inspired by me to transfer into a computing program. The most
  obvious goal any institutional teacher should have is for their students to
  finish with a sufficient understanding of the course material. This is a very
  valid goal and one I hold, however I don't limit myself there. My more
  ambitious goal is to inspire students to want to continue learning. But this
  isn't the only ambitious goal I have. I wish to not just acknowledge my
  positive feedback but critically engage with and improve from my negative
  feedback. The most common theme in my negative feedback (particularly from the
  first few sessional positions I taught) revolve around having too high
  expectations on students. I believe this stems partly from my desire to
  challenge students, but also a personality flaw of lack of patience. One of
  the greatest things about being a teacher is it challenges you to grow as a
  person. It is my greatest goal that as I continue to improve as a teacher, I
  continue to improve as a person.





  
  
#  LocalWords:  pre sessional Javascript Django MySQL GitHub app LocalWords
