#+TITLE: BOPPPS Workshop
#+AUTHOR: Curtis D'Alves

* Pre-Planning

** Who is your audience of learners?
    First year undergraduate computer science students
    
*** Do you know what their accessibly needs are?
    No, but I assume they are capable of using computer interfaces

** How long will you have to deliver the lesson, from start to finish?
   50 min
      
** In what format will the lesson delivered?
   Online, asynchronously, all content will be accessible via the course web page
   (or Avenue)

** What teaching support and resources do you have available to you for the lesson?
   A course web page and server (that I administrate myself)

** Does your Faculty/Department/Organization have its own parameters and expectations for the lesson?
   No, however the lesson is aligned with the intended learning outcomes for the
   course it belongs to


* The BOPPPS Model of Lesson Planning
  | *B*: Bridge-In                  | A brief introduction to the broader topic to be covered |
  |                                 | during the lesson                                       |
  | *O*: Intended Learning Outcomes | What you want your learners to know or be               |
  |                                 | able to do by the end of the lesson                     |
  | *P*: Pre-Assessment             | Determines your learners' existing abilities with       |
  |                                 | respect to the intended learning outcomes               |
  | *P*: Participatory Learning     | Engages the learners as active participants in          |
  |                                 | the learning process                                    |
  | *P*: Post-Assessment            | Indicates whether the learners have achieved the        |
  |                                 | lesson's intended learning outcomes                     |
  | *S*: Summary                    | Summaries the key take-aways from the lesson            |

** Bridge-In
   The first element of a BOPPPS lesson is the bridge-in, which is simply a
   brief introduction to the broader topic to be covered during the lesson.
   
   Here is an example of what a bridge may look like for a lesson:
   #+BEGIN_EXAMPLE
   Bridge for a lesson on heart health: Nine our of every ten Canadians have at
   least one risk factor for heart disease and stroke. Moreover, almost 80% of
   premature heart disease and stroke can be prevented through healthy
   behaviours. One healthy behaviour that has a big impact on heart health is
   eating healthy. In this lesson, you will learn all about what it means to eat
   healthy and how to make eating healthy a habit.
   #+END_EXAMPLE
   
** Outcomes
   See [[file:../../LectureNotes.org][Lecture Notes]] on intended learning outcomes 

** Pre-Assessment   
   A pre-assessment helps you to determine the level of background knowledge or
   experience that your learners have regarding the subject matter of your
   lesson and the ILOs before most of your learning activities begin.

   There are many options to choose from with respect to pre-assessments. You
   could administer a brief online poll, quiz, or survey, or you could even do
   something as simple as ask your learners to rate their current confidence in
   their ability to do each of the ILOs that you articulate for a lesson 

** Participatory Learning
   A lesson plan should have learning activities built into it so that the
   learner will be an active participant in their own learning. See [[file:../../LectureNotes.org][Lecture
   Notes]] on Active Learning for details

** Post-Assessment
   There are two primary types of assessment that you should be able to
   distinguish between – formative assessment and summative assessment.

   - *Formative assessment* is used to monitor learning. It provides ongoing
     feedback that you can use to improve upon your teaching, and that your
     learners can use to improve upon their learning. Essentially, formative
     assessments help you to figure out where your learners are struggling,
     which permits you to immediately address those problem areas. For your
     learners, formative assessments help them to identify their strengths and
     weaknesses, and thus to identify areas where there is room for improvement.
     Usually, formative assessments are low stakes, meaning that they have low
     or no point value.
     + *Some examples of formative assessments are*: asking learners to draw a
       diagram depicting the relationships between the key concepts in a lesson
       subtopic; and asking learners to write and submit a few sentences
       outlining what they feel to be the main point of a lesson subtopic*
       (https://www.cmu.edu/teaching/assessment/basics/formative-summative.html).
       Most of the active learning strategies described in this unit could be
       used as formative assessments.

   - *Summative assessment* is used to evaluate learning at the end of an
     educational experience by comparing it against some standard or benchmark.
     Usually, summative assessments are high stakes, meaning that they have a
     high point value.
     + *Some examples of summative assessments are*: a final quiz, and a final
       project. Information from summative assessments can be used formatively
       when instructors use it to guide how they go about developing and
       delivering subsequent offerings
       (https://www.cmu.edu/teaching/assessment/basics/formative-summative.html).
       This is something that’s highly encouraged.

** Summary

  Finally, the summary gives you the opportunity to revisit key points from your
  lesson - to remind the learners what they should now know or be able to do. It
  also draws your lesson to a close.

  For example, in thinking back to the example that was given for the bridge-in
  earlier, if you were giving a lesson on heart health you could review the key
  take-aways regarding how to eat healthy and make healthy eating a habit, and
  then note that now that the learners are equipped with that knowledge, they can
  work to prevent premature heart disease and stroke.

   
#  LocalWords:  min Pre BOPPPS Summative summative pre
