* Workshops Sign Up Sheet
  
  [[https://docs.google.com/spreadsheets/d/1x0V-4xvkkyEgigR2qvoSQqyfyg9GPVTv2wPY72G4pyk/edit#gid=0][Workshop signup sheet]]

* Workshops I Signed Up For

 | WorkShop 2 | Educational Technologies            |
 | WorkShop 3 | Adult Learning Theories             |
 | WorkShop 5 | Active Learning                     |
 | WorkShop 6 | Facilitating Online Discussions     |
 | WorkShop 7 | Marking Efficiently and Effectively |
 | WorkShop 8 | Research in Teaching and Learning 1 |

* Workshop Post Reflection Instructions
  
Complete a Post-workshop Reflection for each workshop you finish. Under the
“Content” tab on the course’s Avenue to Learn site, there is a folder entitled
“Reflections” with a Word document named “Post-workshop Reflection.” You must
complete a post-workshop reflection (approximately 350 to 500 words in sentence
format) within one week of completing each workshop and submit it to the
corresponding Post-workshop Reflection Assignment Submission Folder
  
* End of Course Reflection Instructions 
  
Write an end of course reflective analysis about your overall learning in this
course (3-4 pages, double-spaced, 12-point Times New Roman font). This analysis
should be informed by personal reflection and a critical review of all six of
your Post-workshop Reflections. Please submit your analysis to the End of Course
Reflective Analysis Assignment Submission Folder on the course’s Avenue to Learn
site before the final full group class meeting.
  

#  LocalWords:  WorkShop
