* Lesson 1 follow-up:
Under our channel’s “file” tab, within each of your folders,
you will see a document titled ‘Facilitator Notes from Lesson 1' which are the
notes I took during our 1:1 discussion and the group feedback circle. You will
also find the completed copies of the Feedback Form that each of your colleagues
filled out after your lesson. The video of your lesson can be found here in the
main channel.


* Lesson 2 prep:
We meet next on February 7, 12:30 – 4:30 p.m. for a theme session with the
larger class, and our small group feedback circle. I will confirm whether we are
meeting in this channel or the General channel first. There are two phases to
what you need to complete prior to that next class. Below I've outlined the
deliverables, by date:
** 1. Due 12:00 Noon on Friday, February 4: 
	
 * Review the feedback and notes from Lesson 1 file in your folder  
 * Watch the video of your Lesson 1  
 * Add your goals for Lesson 2 to the Goals document in your folder.  
 * Prepare and upload your Lesson 2 materials (video? handouts? links? etc. -
   check out the post below for ideas) to your own folder, to be viewed
   asynchronously by your peers. Feel free to organize your folder however you
   like as we continue to populate them with files! Please post a message in our
   channel instructing everyone where to find your materials so we all know they
   are ready for viewing.
   * *Note* that you have 10 minutes of your peers’ attention in total for
     completing your lesson. This means that you can’t prepare a 10 minute video
     as well as other asynchronous work on top of that; however, you could do
     something like teach for 5 minutes on video and then launch a post
     test/summary activity that should take the learner 5 minutes
 * Visit the "Lesson 2" sub-folder in your folder 
 * Fill out the document titled "Self-Reflection for Lesson Two" 
 * Visit the "Feedback Forms" sub-folder in your folder 
 * Look at everything in the "Lesson 2 & 3" subfolder, and select which form you
   want your peers to fill out about your lesson
 * Post a note of which feedback form you’d like everyone to complete in your
   post in our small group channel about your lesson.
   
*Note*: I'll be looking at your Goals, your Lesson 2, and your Self-Reflection
in advance of our next synchronous session.

** 2. Due before we meet at 12:30 p.m. Monday, February 7: 
 * Visit your peers’ folders and complete their asynchronous lessons. 
 * Create a copy of their selected feedback form and fill it out. 
 * You can save it to their folder whenever you complete it, or just after class. 
 * Prepare what you’d like to share during the verbal feedback discussions when we meet.  
 * Please let me know if you have any questions or concerns about anything
   listed above by posting a response below. If you want to touch base about
   your Lesson 2, I’m happy to do so! Please send me a message on Teams or email
   me at ~dycel@mcmaster.ca~.
